= Introduction

== We Are the Cause of the Drug Violence to the South

If you look into history you will see that the Mafia grew powerful during prohibition. Today's drug cartels and gangs are the manifestation of the drug wars that we started. The mass immigration from the many countries to the South of the United States is an attempt to move away from the violence that has been caused by the drug cartels.

However, things go further too, because we are using the product here in the United States and ignoring what had to happen for the product to get here. This attitude in relation to cheap mass-production of textiles, and attitudes of supremacy, that led to chattel ownership of people, forcing humans-beings to work as if they were nothing more than machines, automating cotton. 

If anything, it's important for us to understand what our consumption habits do across the globe, and how those habits affect other people's lives, and reflexively, how they affect *our* lives as well.

If we want to fix the cartel violence, and stop  we have to undermine the power of the cartels and manage our consumption.

* Opioids
* THC
* CBD
* Highly regulated drugs with rehab time.

== Children and Brain Development
We know that alcohol and marijuana have deliterous effects on a maturing brain. It is well established that marijuana use inhibits the development of the myelin sheath before it has had a chance to fully develop. Alcohol has shown to impair the growth of various brain structures.

As such, the relationship with drugs and children must be more complicated than it is with adults.

All of the levels are still being reviewed and can be revised as more information on testing is understood.

=== 16-Years
Along with the view of children progressively becoming adults, I'm recommending that starting at the age of 16 children who are carrying 
their legal ID with them, and under the supervision of parents, be allowed no more than 0.6 oz of alcohol in the period of 1 day 
(approximately half of one beer), and if on testing the 16-year old's alcohol level to found to exceed 0.03 % BAC, the provider will, per
minor overprovided, be fined $500 and jailed for 2 nights. The minor will also be fined $500.

A saliva-based Δ9-THC found in excess of 5 ng/mL (an amount that can only be administered through dilution). The fines for providers and 
for minors, in excess of what is listed, will be the same as for alcohol. Hair testing demonstrating more than 0.05 pg / mg is enough to
have the minor placed in a low-level minor rehability center, and may also be indicative of a call to Child-Protective Services.

CBD is not to be tested for, and is fully allowed in all cases.

Alcohol or THC of any quantity will not be allowed if the 16-year old will be operating a vehicle. In that the parent's supervision is required,
the parent is also responsible for the safety of the child during that time.

=== 18-Years
At age 18, the limit becomes the minimum of 1 drink over the period of an hour or 0.04 % BAC, and the limit will be the same for
operating heavy machinery, including vehicles.

The THC limits for an 18 year old remain the same as those for a 16 year old.

=== 20-Years
At age 20, the limit becomes the minimum of 1-and-a-half drinks per hour or 0.06 % BAC, and the limit is 0.04 % BAC for
operating heavy machinery, including vehicles.

A saliva-based Δ9-THC found in excess of 8 ng/mL (an amount that can only be administered through dilution). Operating heavy machinery
(including a vehicle) beyond the 8 ng/mL results in the same penalties as for exceeding the alcohol limits. Hair testing demonstrating 
more than 0.1 pg / mg is enough to have the individual placed in a low-level rehability center for no more than 7 days on their first
offense.

=== 22-Years
At age 22, the limit becomes 0.07 % BAC, and the limit remains 0.04 % BAC for operating heavy machinery, including vehicles.

A saliva-based Δ9-THC found in excess of 10 ng/mL (an amount that can only be administered through dilution). Operating heavy machinery
(including a vehicle) beyond the 8 ng/mL results in the same penalties as for exceeding the alcohol limits. Hair testing demonstrating 
more than 0.15 pg / mg is enough to have the individual placed in a low-level rehability center for no more than 7 days on their first
offense.

=== 25-Years
At age 25, the limit becomes 0.08 % BAC, and the limit remains 0.04 % BAC for operating heavy machinery, including vehicles.

There is no THC limit for an individual over 25 years of age. A saliva-based Δ9-THC found in excess of 10 ng/mL  administered through dilution). Operating heavy machinery
(including a vehicle) beyond the 8 ng/mL results in the same penalties as for exceeding the alcohol limits. Hair testing demonstrating 
more than 0.15 pg / mg is enough to have the individual placed in a low-level rehability center for no more than 7 days on their first
offense.


=== 30+ Years
Starting at age 30, the limit becomes 0.25 % BAC, which is the beginning of alcohol poisoning, and the limit remains 0.04 % BAC for
operating heavy machinery, including vehicles. Near the level of alcohol poisoning, a person's mental intoxicated mental decision-making
does not reflect their sober mental state, and anyone evidenced to entice, suggest, or force additional drinks onto someone who is
reaching the levels of alcohol poisoning can be jailed for 30-days and face assault charges. If the individual dies as a result of
alcohol poisoning, any and all persons who are evidenced to be encouraging or forcing alcohol will face manslaughter charges.

=== State Law Overrides
These laws are a minimum responsibility and do not reduce the requirements of any state laws in regard to alcohol consumption.

=== ID Requirements
You are not to be sold alcohol without a valid state-issued ID detailing your age, with picture. If you are found to be falsifying your
ID in order to drink or do drugs illegally, you can be faced with 30-days jail and a $2000 fine.

== Managing Drug Dependency and Abuse
This is a problem with prescription drugs as much as it is a problem with illicit drugs.

== Managed Legalization of Drugs
