= Education





The biggest problem with education has always been, and will always be: motivation.
That’s not just motivation for the students, but the educators, the parents, and those that support the educators too, such as business.
That’s not just about the level of motivation but the direction of motivation too, such as “why are we teaching?” and “what should we teach?”.
Firstly, we must recognize some things:

* Education is daycare and therefore, daycare should also be educational. In this respect, parents should always be teaching too, and it’s important to understand that a child should be taught every moment of the day (it takes a village), even while they are playing (which is the activity that imparts the most wisdom). All encounters are responsible for the education of a child, but only the parents and teachers are (usually) accountable.
* A good education leads to good citizens who know to recognize and react to political rhetoric, how to parse and read technical and scientific implications (even if outside of their expertise), and how to perform jobs and tasks within their expertise.

Supplementally, if we are going to understand **how** to teach, we must understand both pedagogy and andragogy, recognizing that children are not adults, and adults are not children, and each learn in different ways.

* Memorization may be a beneficial talent to have, and should be cultivated, but it does not aide in the application and general usage of the skills being taught
* Intuition (usually via analogy) is a basis for the human mind to understand things, and must be cultivated first. Then the rational part of the mind can be employed, via formal definitions, to specialize and clarify lessons. Finally, experience, and especially application, will cement knowledge far above and beyond any of these. The mind needs this order of learning things.
