= Inequality and Poverty

:toc: right

= Abstract
My claim is that people are not as interested in income inequality as they are about:

. The misery of abject poverty -- a high concern for those dealing with it such that, after working several jobs, they still must choose between electricity and food
. Inequality of influence -- a concern for both those who deal directly with it, and those that are concerned for our democracy, money captures interests in our government
. The viscious cycle -- when intergenerational mobility is weak, then rich children stay rich, and poor children stay poor, regardless of how much personal investment and work they do

= Intro
People typically talk about inequality in terms of money. However, my argument will be that it's actually secondary to what people are
really concerned about: influence. However, money appears to be directly proportional to influence, and so people relate the two. People are also related to money, because emergencies happen, and without money, it creates a viscious spiral when one emergency destroys their lives. Additionally, poverty has many effects that are not only monetary.

= The Root Concerns of Poverty

The affects of poverty aren't simple to delineate. Poverty doesn't end with choosing between food and heat in the winter. It doesn't end with putting your child on the bus instead of driving them. It includes working 2 or 3 jobs in order to pay the rent, the food, the heat, and this affects the children who do not have the kind of social, mental, and life instruction needed to develop the skills for adulthood. Poverty is the desperation to leave instead of stay. Poverty is the constant fighting over money, that continue with children the next day at school.

Poverty is by far the largest influence inhibiting a good education. With hope, it can serve as a drive to strive. Without hope, it leads to an attitude of asking, "why should I try?".

== Multiple Causes of Poverty

So, it's not poverty alone that must be dealt with, but it's also changing attitudes of fatalism into attitudes of hope.

Poverty has many causes, many personal, some cultural, but most are systemic. The personal affects are there because of the systemic causes, further adding to the viscious cycle. There are plenty of people that want to ignore the systemic causes altogether, in order that they can either claim immunity from accountability, or due to the fact that they too experience much of the same misery.

=== Poverty and Minorities
To be blunt, poverty is universal. You cannot avoid it by being white, straight, male, cisgender christian. However, the amount of daily struggle in communities of color, women, LGBTQ, and non-christians will often make things every so much worse. Still, we must all be allies, working together to deal with poverty together. 

People are not going to understand what you are going through, and calmly explaining why things are different is the best way to change people's understanding. We are not going to fully understand each other, and some concessions are going to have to be made to that end, but it doesn't mean that the push to make things better is futile either.

=== Wage Growth Stagnation
In the economics of supply and demand, most people understand that an oversupply of labor decreases wages, and that scarcity increases wages. However, the oversupply can be related to many things, and the typical culprits are either problems that are:

- intractible
-- wages have not caught up globally, and yet globalism is necessary maintain an economy in international trade, until then cycles between offshoring (due to expense problems) and onshoring (due to quality problems) will continue until there is more of an even playing field globally; attempts to halt globalization are attempts to wreck our own economy
-- tasks that can be automated will be automated, and all that can be done is to delay the inevitable
- irrational
-- especially in technology, instead of taking on and training labor for domain-specific knowledge, companies are creating a viscious circle of requiring experience that limits any newcomers
-- loyalty between employees and employers is at an all time low, and there doesn't seem to be any care to deal with this as a problem
-- long-term unemployment leads to perception of unemployability
- existent, but not as bad as it is made out
-- immigration does depress wage growth, but is not at the levels that it are made out to be, since immigration also increases jobs

=== Poverties and Attitudes

* Attitudes of "never going to get better"
* Attitudes towards those who have served in the armed forces
* Attitudes towards those who have served time


Some of the problems are not

It is definitely the case that poverty is related to inequality

= The Root Concerns of Inequality
People understand very well that there will always be people more skilled, more productive, more determine, and sometimes just plain more lucky or more willing to break the rules, and therefore will be more rich than others. Marx failed to account for Zipf's Law when it came to discussions about equality. 

On the other hand, it's not to claim that these rich people are somehow better people, because they have more money. The public understandsthat money isn't everything, but there is a tendency to discuss things in terms of "deserving" and "undeserving" when it comes to money.

Trying to break down who deserves what immediately devolves into factions arguing things about people's lives which end up having no realrelevance to the situation. The fact is, people have a history of being notoriously bad at determining who deserves things, but we are often still attempting to make such judgements about people we have never met.

In some regards, this is necessary, in order to help deter crime and exploitation, especially when it is exceedingly obvious that 
exploitation has occurred.

For the most part, people are content with a little inequality, because they want to know that if they work hard that they will not just
survive, but that they will thrive instead.

The concern is still there. People are not only not thriving, many are abjectly miserable.


= The Root Concerns of Poverty

== Immiseration

== Inequality of Influence
To key in on the concerns that the public has, it pays to remember that they are people with their own concerns and that they want for
their concerns to be heard. Oftentimes the expectations from others exceed the potential, and that leads to disapointment in every that
such a mismatch occurs.

There has been so much talk over the years about power, hegemony, and sway, but it actually comes down to what people want more than
anything else: influece. Most people don't really want complete control over every aspect of their lives, and are willing to resort to
giving some control over to automata such as artificial intelligence, calculators, washing machines, safety systems in vehicles, and
other computerized and automatic things. We want the influence to decide how these things work in relation to us, but we'd rather not
do everything ourselves.

=== What the Public Thinks When They Say "Elite"
To an average person, when they use the term "elite", the meaning is "someone with influence". It's not a term that means "rich" or
"skilled" to the average person the way the term means to most. Instead, the feeling conjured up is someone who can be heard.

Oftentimes, it seems as if people don't want to listen to the "elite" in their "ivory towers", but what they are actually claiming is
that "those with the influence are not listening to the concerns they have". The word "elite" has just become a perjorative for someone
who cannot understand the everyday issues that the person has to deal with.

On the other hand, no one can truly walk in each other's shoes, and so there are often things that the public doesn't get about the daily
lives of those they consider to be "influential".

However, this is why Californian's are considered "elite". This is why politicians are considered "elite". It's why academics, the media
personnel, and so on are considered "elite". The perception is that there is more influence on and over their lives.

=== Representation

This is the purpose of the representative in a representative democratic republic such as our own. The representative is supposed to
take our concerns, read through and write the legalese of all of the future laws, and vote for those that are the best. The average
person then asks themselves, "but best for whom?".

In the public sphere, divorced from discussion of legal policy, the inequality of influence is also felt in numerous ways by various
people. If you are at all interested in why we are in our current standing, it's due to perceptions that are definitely not ungrounded:

* In terms of class:
** The average worker perceives that the "elite" don't listen to them
** The average middle-class to lower-class individual perceives that "money = influence" and that they have none

* In terms of demographics:
** The average minority perceives less influence in their lives than members of the majority groups, and calls the influential anything 
    from: "the hegemony", "the patriarchy", and so they have started several movements:
*** Black-Lives Matter - because of perceived lack of influence in the justice system and in the relationships with police forces
*** #MeToo and #TimesUp - because of perceived lack of influence in the workplace and in the justice system
    
** The average member of the majority group perceives influence as zero-sum, and that they are losing theirs, and has formed into the
    Alt-Right, and various other right-wing groups
    
* In terms of information:
** The average person perceives that their concerns are not being reported (media-bias)
** The average person perceives that their concerns are not being well-studied and described (anti-intellectualism, conspiracy,
    anti-academia, and anti-science)

Ultimately, people want representation, and they know that, if the squeaky wheel gets the oil, then it has turned into a squeek-match to
outspeak each other on every subject.

Expectations and pressure and stress

== Summary of the Root Concerns

- Immiseration
- Inequality of influence
