= Rhetoric and Polemic



= Responsibility, Accountability, Agency, Authority, Causation, and Blame

These words are often conflated, and they are conflated to the detriment of everyone who use them and who hear them. It would benefit everyone to discuss the meanings of these words and understand them fully before they start to use them.

== Responsibility

Literally, "The ability to respond". I could say all day that the biggest problem that people have in general is that no longer believe that they have responsibility for what has happened to them. This is inherently true, because if we are using the word *appropriately*, it means that we are "enabled" to make changes to our lives. However, what we can argue about is the effect and effectiveness of the changes we are capable of making.

I once witnessed an older couple in a line for a buffet. Both the man and woman were of an age where walking and bending were difficult for both of them. The lady's purse fell over, and before she could do anything about it, a young boy picked up much of the change and handed it back to her. The gentleman's immediate claim, "Thank you lad, but that is not your responsibility". It was at this moment that the boy said, "I just did what I could". The lad understood at that age, without really knowing the difference between the words that he had the ability to respond to the situation, therefore making it his responsibility, even though the boy was neither accountable to the consequences nor to blame for what happened.

Likewise, responsibility is ubiquitous. It is indeed something that we can take on at a whim. People are often afraid of responsibility, because they are afraid of blame. Likewise, it is often wise to recognize when to respond and when not to. Response and action are not always the beneficial way to go, because timed response and delayed actions can often lead to better outcomes.

== Causation and Blame

Without heading into the Quantum quirks of causation, we usually interpret causation as 

== Blame and Accountability
